version: '2'
services:
      tomcat:
         image: 'tomcat:9.0.62'
         restart: on-failure:3
         ports:
             - '8082:8080'
         volumes:
             - '../../../target/betApi.war:/usr/local/tomcat/webapps/betApi.war'
         networks:
            - my-network    

      pgdb:
          image: 'postgres:13.1-alpine'
          mem_limit: 1536MB
          mem_reservation: 1G
          container_name: pgdb
          environment:
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=pgsqlP@ss123!
          ports:
              - "5432:5432"
          networks:
            - my-network

volumes:
    tomcat_data:
        driver: local
    
networks:
  my-network:
    driver: bridge    

    